import {StyleSheet} from 'react-native';

export const s = StyleSheet.create({
  conteiner: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  header: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  Title: {
    fontSize: 18,
    fontFamily: "Arial",
    fontWeight: "700",
    color: '#111827',
  },
  bntCreateAccount: {
    width: "60%",
    height: 44,
    backgroundColor: "#2563EB",
    paddingHorizontal: 12,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 12,
    borderRadius: 10,
    alignSelf: 'flex-start',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  areaRender: {
    width: "100%",
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  modal: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    padding: 16,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 32,
  },

  titleModal: {
    fontFamily: "Arial",
    fontWeight: "700",
    fontSize: 20,
    marginBottom: 16,
    color: '#111827',
  },
  inputRow: {
    width: '92%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  inputIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#EEF2FF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  input: {
    flex: 1,
    height: 44,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 10,
    paddingHorizontal: 12,
    fontFamily: 'Arial',
    color: '#111827',
  },
  primaryBtn: {
    width: '92%',
    height: 44,
    backgroundColor: '#2563EB',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    marginTop: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  textPrimaryBtn: {
    color: '#FFFFFF',
    fontFamily: 'Arial',
    fontWeight: '700',
    fontSize: 16,
  },
  secondaryBtn: {
    width: '92%',
    height: 44,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  textSecondaryBtn: {
    color: '#2563EB',
    fontFamily: 'Arial',
    fontWeight: '700',
    fontSize: 14,
  },
  flatList: {
    marginLeft: 10,
    width: "100%",
    height: 200,
    backgroundColor: "transparent",
  },
  grupoAccount: {
    width: 260,
    minHeight: 140,
    gap: 6,
    backgroundColor: "#FFFFFF",
    marginTop: 24,
    borderRadius: 12,
    padding: 12,
    marginRight: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  text: {
    fontFamily: "Arial",
    fontWeight: "700",
    fontSize: 13,
    color: '#111827',
  },
 
  bntFlat: {
    width: "100%",
    height: 40,
    backgroundColor: "#EF4444",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    marginTop: 8,
  },
  textBnt: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontFamily: "Arial",
    fontSize: 14,
  },
  textcreateAccount: {
    color: "#FFFFFF",
    fontFamily: "Arial",
    fontWeight: "700",
    fontSize: 14,
  },
  ListVazia: {
    width: "100%",
    height: "20%",
    alignItems: "center",
  },
  textListVazia: {
    fontFamily: "Arial",
    color: '#6B7280',
    fontSize: 14,
  },
});