import {StyleSheet} from 'react-native';

export const s = StyleSheet.create({
  conteiner: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
  },

  areaAdd: {
    width: "92%",
    marginTop: 20,
    backgroundColor: "#FFFFFF",
    padding: 16,
    justifyContent: "center",
    alignItems: "stretch",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  title: {
    fontFamily: "Arial",
    fontSize: 20,
    color: "#111827",
    marginBottom: 16,
    fontWeight: "700",
  },
  inputRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
  },
  inputIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#EEF2FF",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  input: {
    flex: 1,
    height: 44,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 10,
    paddingHorizontal: 12,
    fontFamily: "Arial",
    color: "#111827",
  },

  areaBntAdd: {
    width: "100%",
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
    marginTop: 8,
  },
  primaryBtn: {
    width: "48%",
    height: 44,
    backgroundColor: "#2563EB",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  dangerBtn: {
    width: "48%",
    height: 44,
    backgroundColor: "#EF4444",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },

  textbntAdd: {
    fontSize: 16,
    fontFamily: "Arial",
    color: "#FFFFFF",
    fontWeight: "700",
  },
  buttonVoltar:{
    width: "92%",
    height: 44,
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  textButtonVoltar: {
    fontSize: 14,
    fontFamily: "Arial",
    color: "#2563EB",
    fontWeight: "700",
  }
});